### ISSUE TITLE
Error: Attempted to assign to readonly property.

### ISSUE THREAD

**Issue by frecklebit** [StarterSquad/startersquad.com#17]
I have my Angular app set up exactly like this but in my controller I get "Error: Attempted to assign to readonly property." error. This is on the $scope variable. It's as if it's not including the $scope variable. Also, how can I pass a service factory to the controller?

**Comment by frecklebit** [comment]
Stupid cache.

**Comment by Maqsim** [comment]
@adamcole83 :)
