### ISSUE TITLE
how to add another plugin

### ISSUE THREAD

**Issue by goldalworming** [StarterSquad/startersquad.com#4]
Hi, how to add antoher angular plugin that needs jquery and jquery plugin such as
http://blueimp.github.io/jQuery-File-Upload/angularjs.html

I'm having trouble add configuration in require config..
can you have some example??

**Comment by iwein** [comment]
If you look at another plugin, for example angular-resource it should work similarly.

We're using bower for dependencies, so you should do something along the lines of:
1. `bower install …`
2. add library to build-config.json
3. declare dependency where you need it
4. use

**Comment by dmitryevseev** [comment]
@goldalworming Do you need any more help?

**Comment by goldalworming** [comment]
actually I thought we could add library dinamically

controller A need a,b,c directives
controller B need b,c,d directives 
and directives load asynchronously..but I don't think it handle this..

thanks

**Comment by dmitryevseev** [comment]
It definitely can be handled. For not angularjs dependencies at component/module level (controller, service, module). For angularjs dependencies at module level only (that's the way it works in angular). Requirejs used here in conjunction with angularjs in it's pure state, so you can use it as usual without any restrictions.
